spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #    url: jdbc:h2:file:/Users/sriram/Workspace/HomeFinance/shf-portfolio-service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      #      http://localhost:8080/h2-console
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: "never"
  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: validate
