--MERGE INTO PORTFOLIO KEY(ID) VALUES (1, 'Renga Portfolio', 'Renga', CURRENT_TIMESTAMP, null, null);
--MERGE INTO PORTFOLIO KEY(ID) VALUES (2, 'Omana Portfolio',  'Renga', CURRENT_TIMESTAMP, null, null);
MERGE INTO PORTFOLIO (ID, PORTFOLIO_NAME) VALUES (1, 'Renga Portfolio');
MERGE INTO PORTFOLIO (ID, PORTFOLIO_NAME) VALUES (2, 'Omana Portfolio');