--CREATE TABLE IF NOT EXISTS PORTFOLIO
CREATE TABLE PORTFOLIO
(
  ID              			INT NOT NULL AUTO_INCREMENT,
  PORTFOLIO_NAME           	VARCHAR(150) NOT NULL,
  CREATED_BY				VARCHAR(150),
  CREATED_ON				DATETIME,
  MODIFIED_BY		        VARCHAR(150),
  MODIFIED_ON  				DATETIME,
  PRIMARY KEY     (id)
);